version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx_test:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - test-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - flask
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  settlegram:
    build: ./SettleGram
    command: python -u main.py
    env_file:
      - ./secrets.env
    environment:
        PYTHONUNBUFFERED: 1
    depends_on:
      - mongodb
    networks:
      - test-network
  flask:
    build: ./flask-app
    volumes:
      - ./flask-app:/code
    env_file:
      - ./secrets.env
    environment:
      FLASK_ENV: development
      PYTHONUNBUFFERED: 1
    expose:
      - "5000"
    depends_on:
      - mongodb
    networks:
      - test-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db-data-test:/data/db
    networks:
      - test-network

volumes:
  db-data-test:

networks:
  test-network:
