version: '3'
services:
  flask:
    build: ./flask-app
    env_file:
      - ./secrets.env
    environment:
      FLASK_ENVIRONMENT: development
      PYTHONUNBUFFERED: 1
    expose:
      - "5000"
    depends_on:
      - mongodb
    networks:
      - mynetwork
  settlegram:
    build: ./SettleGram
    restart: always
    command: python -u main.py
    env_file:
      - ./secrets.env
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/data/db
    networks:
      - mynetwork

volumes:
  db-data:

networks:
  mynetwork:
