version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx_prod:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - mynetwork
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - power-telegram
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  settlegram:
    build: ./SettleGram
    env_file:
      - ./secrets.env
    environment:
        PYTHONUNBUFFERED: 1
    depends_on:
      - mongodb
    networks:
      - mynetwork
  flask:
    build: ./flask-app
    command: gunicorn app:app --bind 0.0.0.0:5000
    env_file:
      - ./secrets.env
    environment:
      FLASK_ENVIRONMENT: development
      PYTHONUNBUFFERED: 1
    expose:
      - "5000"
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/data/db
    networks:
      - mynetwork

volumes:
  db-data:

networks:
  mynetwork:
