version: '3'
services:
  frictionless:
    build: ./frictionless
    restart: always
    command: python -u main.py
    depends_on:
      - mongodb
    networks:
      - mynetwork
  flask-app:
    build: ./flask-app
    volumes:
        - ./flask-app:/code
    ports:
      - "80:5000"
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
     - ./db-data:/data/db
networks:
  mynetwork:

volumes:
   db-data:
